map_type: costmap           # default: costmap
transform_tolerance: 0.4    # default: 0.2
obstacle_range: 2.5         # default: 2.5 
raytrace_range: 3.0         # default: 3.0

observation_sources: laser_scan_front laser_scan_rear laser_scan_top

laser_scan_front: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /base_laser_front/scan, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
# default sensor_frame : base_laser_front_link
# default data_type : LaserScan
# default topic : /scan_front
# default expected_update_rate : 1.2
# default observation_persistence : 0.0
# default marking : true
# default clearing : true
# default min_obstacle_height : -0.10
# default max_obstacle_height: 2.0

laser_scan_rear: {sensor_frame: base_laser_rear_link, data_type: LaserScan, topic: /base_laser_rear/scan, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
# default sensor_frame : base_laser_rear_link
# default data_type : LaserScan
# default topic : /scan_rear
# default expected_update_rate : 1.2
# default observation_persistence : 0.0
# default marking : true
# default clearing : true
# default min_obstacle_height : -0.10
# default max_obstacle_height: 2.0

laser_scan_top: {sensor_frame: base_laser_top_link, topic: /base_laser_top/scan, data_type: LaserScan, marking: true, clearing: true}

